### ISSUE TITLE
Is better to replace it with New(code,message)?

### ISSUE THREAD

**Issue by cnlangzi** [0chain/errors#2]
https://github.com/0chain/errors/blob/652f4757f34cfa4899009faa7da87c21b67866cd/errors.go#L25

Because it will fail to create error if there are more than 2 argument? Why we don't update it with

```
New(code, message string) *Error
```

It is better to understand and use. if so, the issue https://github.com/0chain/errors/issues/1 is gone too.

**Comment by NoSkillGuy** [comment]
If we mandate the args, then both code and msg becomes mandatory. 

Let's say we want a error with just message
with dynamic args, it's simple and nice. 
```
err := errors.New("new msg")
```
if we mandate `code`, then it's going to be 
```
err := errors.New("", "new msg")
```

**Comment by cnlangzi** [comment]
It is a corner case for errors.New("1st","2nd","3rd"). It can't be checked on build. Actually, it is not fixed. We  just leave it on runtime. 
It is not a good idea.  **Static code checking is better than runtime debugging.**

so I would suggest to refactor it with `New(code, message string)`. 

And yes, it should be disallowed `New("xxx")`. Because we need code and message for an error, right?

if we really need it, please add a new method for it. this is a disadvantage on golang with no overloading feature.
