### ISSUE TITLE
log critical raw error, and throw predefined error variable and traceid

### ISSUE THREAD

**Issue by cnlangzi** [0chain/errors#7]
for a better user and debugging experience, we should have a better error handling

- show friendly error message instead of raw error
- log raw error ,and generate traceid for debugging. it is easier to find  correct raw error in logging system, and trigger DevOps alert.

for example :

```

var ErrServiceUnavailable = errors.New("service unavailable")
if err != nil { //any network/db error
    if errors.Is(err, ErrHasNotShared) {
         return nil, err
    }
    return nil, errors.ThrowLog(ErrServiceUnavailable,err)
}

if shareInfo == nil ||  shareInfo.Removed {
    return nil, ErrHasNotShared
}


var ErrHasNotShared = errors.New("client does not have permission to download the file. share revoked")


func GetShareInfo(ctx context.Context, clientID string, filePathHash string) (*ShareInfo, error) {
	db := datastore.GetStore().GetTransaction(ctx)
	shareInfo := &ShareInfo{}
	err := db.Table(TableName()).
		Where(&ShareInfo{
			ClientID:     clientID,
			FilePathHash: filePathHash,
		}).
		First(shareInfo).Error

	if err != nil {

    if errors.Is(err, gorm.ErrRecordNotFound) {
        return nil, ErrHasNotShared
    }

		return nil, err
	}
	return shareInfo, nil
}


```

**Comment by NoSkillGuy** [comment]
@cnlangzi What you said is correct, but should it be the responsibility of this package? 

This package should give the actual error, it's up to the client who is using this package on how to give a friendly message and log it for debugging purpose right

**Comment by cnlangzi** [comment]
> @cnlangzi What you said is correct, but should it be the responsibility of this package?
> 
> This package should give the actual error, it's up to the client who is using this package on how to give a friendly message and log it for debugging purpose right

check code example on PR https://github.com/0chain/errors/pull/8
